### ISSUE TITLE
Display packages version in the list

### ISSUE THREAD

**Issue by fsdiogo** [maticzav/emma-cli#12]
Hey @maticzav, thanks for this awesome tool 👍 

This is just a suggestion, not really an issue, but it would be great if we could see the packages version in the search list!

What do you think?

**Comment by maticzav** [comment]
Hey @fsdiogo 👋 

I love your idea! Are you familiar with Ink? Even if you are not, I would love to see you implement this if you have some spare time - I can also help you if anything "weird" comes your way, but it should be pretty simple to comprehend.

**Comment by fsdiogo** [comment]
Never heard about Ink but as I'm familiar with React it should be pretty straightforward 😄

I'm a bit low on time at the moment, but when I have the chance I'll make a PR with this feature!
