### ISSUE TITLE
FYI: new tink/npm search probably being derived from this

### ISSUE THREAD

**Issue by zkat** [maticzav/emma-cli#18]
Heya! I'm Kat, the architect for the npm CLI and [tink](https://npm.im/tink). I just wanted to let you know that your project is super cool and I think is a fantastic candidate for replacing the current npm search (starting off as the new tink search). I've [made a post about it](https://npm.community/t/tink-new-search-ui/3087/2) asking for community collaborators to contribute it, and I'm expecting a variation on your project!

This isn't me writing asking for you to contribute it, by the way. I just wanted to make sure you knew and hopefully were happy to have inspired this improvement. Thanks for the cool project!

**Comment by JureSotosek** [comment]
It's awesome to hear that you found it helpful. 😀

**Comment by maticzav** [comment]
Heyhey 👋, I am so happy to hear that you like Emma CLI. I believe it's high time this project moved to a more suitable parent-project, like Tink for example. I have a lot of ideas of where to go next with Emma and would love to see how we could align them with NPM or Tink. 

Would you be up for a quick brainstorming session some day next week? We could discuss the new version and see whether we could implement it in NPM as well. Let me know what you think! 🙂

**Comment by zkat** [comment]
I think the best thing to do at this stage is probably to collaborate with the volunteer who offered to implement theb Tink version and share your experience there.

As far as getting it into the npm CLI, the main thing you can do here is to draft an RFC and post it to https://github.com/npm/rfcs. I think an info session is a good idea too, but I can't make any time commitments as early as next week because of life reasons. The good thing is the CLI takes its time so there's no rush to meet up and chat. An RFC would still be a fantastic center for starting a discussion though.

**Comment by maticzav** [comment]
You are right! Thanks for pointing me in the right direction. I'll surely file an RFC as soon as things get rolling.

I hope everything's fine and wish you get well as soon as possible. Let me know if you find any spare time, otherwise until RFC 🎉🙂
