### ISSUE TITLE
add the possibility to choose to install as devDependencies when i select a package

### ISSUE THREAD

**Issue by wcastand** [maticzav/emma-cli#21]
Hi, awesome project

I see that we can choose to install packages as devDependencies with the --dev option, but often what happens to me is i search for a package like `yarn add next react react-dom` and then need to do `yarn add -D @types/next @types/react @types/react-dom` as a devDependencies.

I see two way your cli would be awesome, first i can just start searching and when i select a package to install their is some way to choose as a dependencies or devDependencies so i don't have to to quit the search to switch between dev and normal dependencies.

The second way that would be even more awesome is only useful for typescript people but that would be to install as devDependencies the @types package automatically by searching if it exist.

Let me know how that sounds to you and maybe we can work something out :)

**Comment by maticzav** [comment]
Check out v2
