### ISSUE TITLE
Add way to open the repo

### ISSUE THREAD

**Issue by bfred-it** [maticzav/emma-cli#3]
> You might want to give a look at the code too, though. I often find so-called micro packages and then find out that they have huge or useless dependencies. Gotta read that index.js!
> https://twitter.com/bfred_it/status/971684338549977089

**Comment by andylima** [comment]
Yes, I found this tool and thought: "If I could get each repo's URL then this tool would really be useful for me." 😊

**Comment by bfred-it** [comment]
Related: https://www.npmjs.com/package/npms-cli

**Comment by maticzav** [comment]
I love the idea! `npms-cli` is IMO a bit too detailed - I kind of like the simplicity of the current list. Maybe we could, instead of showing the URL, actually display the README in the terminal and you would be able to check it in the detailed view. This could also allow for further version selection, `index.js` preview `dependencies` etc. wdyt?

**Comment by maticzav** [comment]
Ok, @andylima @bfred-it I just got an idea that we could automatically open a README file of the repo if you press right arrow when searching. I first thought of moving everything to Ink - Markdown component and then highlighting the code and everything, but this might be a lot better, wdyt?

**Comment by andylima** [comment]
Not sure if this is what you mean, but pressing right arrow to open a repo's web address (e.g., "https://github.com/maticzav/emma-cli") in the default browser would be ideal to me. Is this what you mean?…

**Comment by maticzav** [comment]
@andylima that’s exactly what I had in mind!

**Comment by maticzav** [comment]
Check out v2 which opens README on double right click. I believe this gives sufficient information about the package.
