### ISSUE TITLE
Multi-select

### ISSUE THREAD

**Issue by bduff9** [maticzav/emma-cli#4]
Love the tool!  One thing you might want to consider looking into is a way to select more than one package at a time with a search.  For instance, if I want both react and react-dom, I type in `react ` and both come up.  However, I have to press enter on React, retype react, arrow down to react-dom, press enter, then press enter again just to install 2 packages.  If I wanted eslint-react-plugin as well, it'd be even worse.

Instead, if I could press space bar or similar to multi-select current packages on the screen, it would make this great tool even quicker.  Thanks!

**Comment by maticzav** [comment]
@bduff9 I love your idea! I tested it myself and I've got to say you are 💯 right! 

I just added it to the new version. Be sure to check it out! 🙏

**Comment by bduff9** [comment]
Cool, looks better.  I appreciate the quick turnaround.  One minor note for you to consider is to have a quicker way now to actually install the packages that are selected.  For instance, back to my original example, I have selected the react, react-dom, and eslint-react-plugin packages.  Now, the only way I can see to actually install these 3 packages is to delete the react keyword I typed in, then press enter.  If there was either a shortcut key to install, or even a selectable option to install below the package search results, I think that would be easier.  If you went the selectable option route, you could even make this conditional so that it only shows up once at least one package was selected.  Either way, I do like the current behavior better than the original, so thanks again!

**Comment by maticzav** [comment]
I totally missed that. I think it's best to revert back as it might cause a lot of confusion to why the packages are not installing - I will add it back once we find a proper solution to both of this problems.

**Comment by caseyWebb** [comment]
I'd suggest mimicking the UX of `yarn upgrade-interactive`

**Comment by maticzav** [comment]
@caseyWebb I love the `space` selection idea, brilliant! I will probably have to rewrite some core modules which I am using now, hence I'll probably delay this a bit to make sure nothing collides with the new features we will be introducing very soon.

**Comment by maticzav** [comment]
Check out v2
