### ISSUE TITLE
Set configuration to choose more than 5 results

### ISSUE THREAD

**Issue by ThomasG77** [maticzav/emma-cli#6]
5 results is really to limited IMO.
If I don't already know the exact package name, I can't really get a list long enough to maybe find the right-one. Feel free to close or keep it as nice to have as it's really a personal opinion.

**Comment by maticzav** [comment]
I love the idea! I think that extending the number of represented results as a setting is a great approach, but maybe implementing pagination or infinite scroll is even a better one as you can then truly search the packages.

The only problem here is that I haven’t figured out the exact key mapping as the current approach would colide with some of the upcoming features we are working on. In general there will be two lists and making one infinite would made switching to the other one impossible.

Maybe you have any suggestion for this?

**Comment by JureSotosek** [comment]
This issue has been addressed in the recent update!

You can now use --limit flag to change the number of packages shown at once!
