### ISSUE TITLE
Use npm if there is an `package-lock.json` file

### ISSUE THREAD

**Issue by tjoskar** [maticzav/emma-cli#8]
Hi,

First of all, great project! 

I'm using yarn in some projects and npm in other. `emma` is however defaulting to yarn due to these lines: https://github.com/maticzav/emma-cli/blob/dfef9efe45ca94b0a74b2648a1d4fe754e4e74ab/src/emma.js#L20-L27

What do you think of checking if `package-lock.json` exist first? Something like
```js
const canAccessFile = promisify(fs.access)
const exec = promisify(child_process.exec)

const isYarnInstalled = () => exec(`yarnpkg --version`, { stdio: `ignore` }).then(() => true).catch(() => false)

const shouldUseYarn = () => {
  return canAccessFile('package-lock.json')
    .then(() => false)
    .catch(isYarnInstalled)
}
```

And then:
```diff
- const yarn = shouldUseYarn()
+ const yarn = await shouldUseYarn()
```

I can create a pull request if you want.

**Comment by maticzav** [comment]
@tjoskar that would be perfect! Create a PR and I'll merge it right away.
